
-- Databse: livesql
-- Description:
-- Apart from v1 we reduced one join and used the channel table to access user id.

SELECT VIDEOS.TITLE, CHANNELS.CHANNELNAME, STATISTICS.likes/STATISTICS.views AS ratio
FROM VIDEOS 
JOIN CHANNELS  ON VIDEOS.CHANNELNAME = CHANNELS.CHANNELNAME
JOIN STATISTICS ON VIDEOS.VIDEO_URL = STATISTICS.VIDEO_URL
WHERE CHANNELS.OWNER_USER_ID IN (
    SELECT USERID
    FROM USERS
    WHERE NAME LIKE '%Marvel Entertainment%'
)
ORDER BY VIDEOS.TITLE ASC;