
SELECT U.NAME AS USERNAME, U.EMAIL, C.CHANNELNAME AS CHANNEL_NAME
FROM USERS U
JOIN CHANNELS C ON U.USERID = C.OWNER_USER_ID
JOIN SUBSCRIBE S ON C.CHANNELNAME = S.CHANNELNAME
WHERE C.CREATION_DATE = DATE '2023-01-01'AND S.SUBSCRIPTION_TYPE ='paid'
GROUP BY U.NAME, U.EMAIL, C.CHANNELNAME
HAVING COUNT(USERID) > 100;